### ISSUE TITLE
My Server does not shows Highcharts

### ISSUE THREAD

**Issue by Merratzz** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#12]
I have setup all things step by step. Everthing working, miner does connect and display at my Pool. But the section for Stats it show only "Loading hashrate chart..." And i don`t know why?

Can you help me with this?

**Comment by mmitech** [comment]
Hello, 

you need to open an account at woopra.com then change [this.](https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/blob/master/mainpage/assets/js/main.js#L42-47)

but before check if your API works http://YOUR_SERVER_ADDRESS/api/get/data/index.php?data=miner_hashrate&range=max&dtx=YOUR_ETH_ADDRESS


Not trying to hijack this project but a new pool that was sponsored by Ethereum project was just [released ](https://github.com/sammy007/open-ethereum-pool), it comes with stratum support which is the most important feature IMO.

**Comment by davembg** [comment]
Why is stratum the most feature?
Everyone hypes stratum - but, with Ethereum, it only reduces the blockchange time.

vardiff is already implemented in this pool, and it actually has a greater impact on mining than stratum.

Stratum requires more resources on the server and in some cases, may actually REDUCE your chances of finding a block. Truth is, if you just throw everything on a single $20 mo. server, it won't be any better than a good getwork implementation.

**Comment by mmitech** [comment]
Stratum is so important because when you have a large pool or a large mining farm, bandwidth and latency is the key of the performance of your pool and respectively miners.

Another thing I will add, I tried this pool software, it is so inefficient and resource hungry that we decided to just stop using it, I couldn't figure how to scale this code and I am sure that http://ethereumpool.co/stats/ have the same issues, php just suck for performance and large scale applications. 

read more here https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/issues/7#issuecomment-184557696

**Comment by mmitech** [comment]
also PHP is great to do fast and easy tasks and/or small projects, and the skill of this developer can be seen here, being new to Ethereum then, I've learned a lot by looking at his code... but it is not efficient.

**Comment by Merratzz** [comment]
Ok thanks a lot for quick response.

I will watch and probably try the new code of the stratum pool. It is very
interesting.

Here you can find out s little bit more about my pools
https://www.mastermining.net

But a this time not a lot miners are on my pool only on tagcoin pool is a
big player...because i have migrated my server this week to newer.

Best Regards

Mike (Merratzz )
Am 28.04.2016 5:54 PM schrieb "Mourad Ilyes Mlik" <notifications@github.com

**Comment by davembg** [comment]
Stratum is important to YOU. If you only want to spend $40 a month on a server that generates $400 in fees then yeah...whatever.
PHP scales just as well as node - if you know what you're doing.
You're comment about PHP is hilarious, and just plain mistaken.
You LIKE node, I assume - I like it too.

It's much harder to debug and track down errors in node/redis than PHP/MySQL - been there.
This code is alpha, works fine if you re-write it and use HHVM instead of PHD (push here dummy) PHP

Sammy007's code looks pretty good, and node-stratum is mature.

My main concern is it's punishing the wallet with 4 RPC calls per second.
I'm planning on modifying geth to push the newwork info to memcache on blockchange - much more efficient.
I suggest everyone do the same.

**Comment by mmitech** [comment]
did you [click on the link](https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/issues/7#issuecomment-185116759) where I pointed you to a discussion where I had a 24 core barebone server with 96 GB of Ram and SSDs, where I reduced work [processing ](https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/blob/master/block_processing/process_work/index.php#L56) and increased [minimum diff ](https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/blob/master/mainpage/index.php#L13) and diffrent setups of php5-fpm, HHVM and php7.0-fpm as well....  nothing really helped.

Just try to mine in this [pool ](ethereumpool.co/) take a look at your gethminer and come back with an opinion.

PS: I do a lot of php development, a bit more nodejs, some C++ and python.... and I can tell you that [PHP sucks for performance app and large scale ops.](http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=nbody)

**Comment by Merratzz** [comment]
Ok i have setup woopra.com and change in my code.  When i try api i get an database error. And what should i do on Whoopra more. Click something or only write my Project id in Code?

**Comment by Merratzz** [comment]
here is the site http://etherum.mastermining.net/ probaly it can help for

**Comment by davembg** [comment]
I did read your link, mmitech - and I laughed a bit, I have to say.
I think you changed all the wrong things, for all the wrong reasons.

I've got it running (mosly re-written) on (2) tiny VM's at 10% load with only a few users.
Painfully, it's geth that has the hardest time keeping-up.
The Nginx/HHVM will keep-up with 100x the activity - GETH IS THE PROBLEM.
The more it mines, the more it suffers - funny thing is, it's written in GO, one of faster on your "php sucks link".

Merratzz - DON'T USE THIS CODE - YOU HAVE TO RE-WRITE A LOT OF IT TO GET IT TO WORK.
Use sammy007's node pool,

**Comment by mmitech** [comment]
check that all includes location are right, in every single page you need the config and [BigInteger](https://github.com/karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source/blob/master/mainpage/index.php#L3)to be included correctly.

You will have to do many more rewrites anyway, so if you don't have the skills just stop now, Geth rpc also changed a bit so you have to look at that also.

**Comment by mmitech** [comment]
@davembg ok, now you've wiped my 8 years of experience of ops and DevOps in two sentences, I would love to try your improvements on the 2 "tiny VMs" we have at least 50 GHs in our DC, I will gladly point 5-10 GHs to test your code.

PS: again, ethereumpool.co/ is a live example of how this PHP suck for large scale backend ops.... take php-MPOS, it works fine because it only serve the frontend and do simple backend share/stats calculations, all the serious mining handling is done by NOMP or Stratum-mining (python).

**Comment by Merratzz** [comment]
ok thanks i wil try to get running worker running one uncle block already have found yes the bigInteger i have change all with jedit serach replace the www4....with my domains. I thins now there only something to do but what,

@davembg    there is no quick start out for this code ?

**Comment by Merratzz** [comment]
@davembg there is no quick start out for this code ?  For me the best way is a Nomp startum with mpos but there is noting good code there with stratum implemation only something found from supernova but i did not get to work with this.

**Comment by Merratzz** [comment]
Why the api not running i think thats why the stats site only show me  

4 times Loading hashrate chart...


Loading balance chart...




Loading miners chart...




Loading workers chart...

**Comment by mmitech** [comment]
@Merratzz  because the JS script can't fetch any data, it says database error when I visit: http://etherum.mastermining.net/api/get/data/index.php?data=hashrate&range=max

check if you are calling the config correctly...

**Comment by davembg** [comment]
Merratzz - no, there is no quick start. This code is ALPHA and basically a framework and methodollogy for building a pool.
Some good ideas here - like using memcache for getwork calls and reducing diffs in getwork.

mmitech - I don't mean to doubt your experience, deploying a pool on a single server is what I was laughing at. For your load you need 3-4 servers and LB on the frontend.
You seemed to think that heavy load and latency was due to HHVM/PHP and I didn't see enough data on your traffic - just load. You can't reduce heavy load and latency load with faster code, it just uses more resources. Load and latency are usually reduced horizontally, not vertically.

I would be glad for 1GH to 5GH on my beta pool, using HHVM/MySQL.
Geth will still complain FAR more than Nginx, I bet.
Any more than 1-5 and I have to spin-up more machines for LB.

We agree this code has a lot of stuff going-on that really doesn't need to happen:
Validating every share in the shares table every minute during the round.
4 RPC calls per second to the wallet for getWork
Calling home using woopra.com code (JUST REMOVE THE JS, ugh)

Why in the world would you need a single monster machine for a pool?
Many smaller machines provide redundancy and better load distribution.

**Comment by mmitech** [comment]
Having 4 VMs in one Hypervisor is the same like having 1 barebone server that host the 4 VMs... never ever try to scale your hardware before optimizing your code as much as possible. 

I've seen well optemized code run the same load on a single VM that runs on a 6 vcores, 8GBs and SSD, if we talk about scaling, having a DB barebone optimized server for Mysql and one load balancer with 3 barebone servers for the backend should be more than enough if you are running a large pool such as dwarf.

**Comment by davembg** [comment]
You have too make sure your VMs are on unique hardware, which I always do.
Saying "never" in this business is knee-slapping funny - never works that way:)
Many times the REASON you scale is because of bad code that's too expensive or time consuming to optimize.

Load isn't everything, it's response time and availability that are key.
Lower load doesn't always produce faster response, especially during testing.
You won't have optimal response and HA with a single piece of hardware, right?

I too, have a lot of experience with code, MySQL in large installations, Cisco data and voice, and Linux/Solaris deployment/management experience. I have several VM's that are 8yrs old.....just sayin'

If you hit my pool with 1-5GH and it falls over, that would actually be of GREAT help to me. 
I'll be happy to post results with my 1GB single-core nginx/hhvm VM.
I'm betting node won't do much better, and I'd love to find out.

donkeypool.com is the URL.

**Comment by mmitech** [comment]
I thought you would share your code with us to benchmark it... I am not going to change 50 workers settings to test on your pool (especially that we are using stratum proxy).

open source your code and I promise it will get tested sometime soon.

**Comment by davembg** [comment]
I will share my code, because it's based-on karek's.
I would just like to fine-tune it a bit.

I certainly understand why you wouldn't want to move 50 miners over.

Lemme know if you want that geth hack for getwork - so you don't have to punish your wallet instances with 4 requests per second.

**Comment by Merratzz** [comment]
@mmitech ok yes i have check the confg.php
I seem be good, because my own miner does correct write in sql database. When i show in poolhashrate are always new listings. So in config i setup only database Connection settings, correct? Maybe I need to download the code once again and have made errors at change?  Or are there other depencies to intstall? Like something for JS script. nodejs  + npm is already installed. I will try again tomorrow.

**Comment by davembg** [comment]
@Merratzz there are many edits to be made and you have to use geth 1.3.x or the the RPC calls will fail with an "unmarshal" error. At least that's what I experienced.  I would strongly advise you to use sammy007's pool code, this code won't likely be updated.

**Comment by karek314** [comment]
@Merratzz Just change all 
`or die("Database Error");`
in **/api/get/data/index.php**
to 
`or die(mysqli_error($mysqli));`

And let us know with results or fix it yourself if you understand source of the problem. im guessing that maybe some path issue with db config.

According to code, as far i know this code still works, even that it was written in early geth versions. I can fully agree that code looks unreadable and messy, and there are few things that could be removed and obviously improved, specially in terms of visibility. But as i have mentioned that was written fast, in few hours work, i haven't even check some things. Reason was just to help community do not centralize with mining. 

Im also not understanding concerns with performance. 
[](https://eth.pp.ua/stats/)
eth.pp.ua works fine with 30ghash connected. AFAIK, they have one machine with 12 cores.
I was running this pool without any problem under 250 workers, also on one machine.

I can also agree and confirm that geth is not efficient at all, specially shares verification is very heavy and take lots of resources, it can be enabled or ignored, but then anyone can easily modify diff and cheat pool to receive higher rewards per share.

According to pool efficiency the most important thing is to run on dedicated server. Most VPS provide very unfair resources, i have been using Digital Ocean for some time for some projects, and they have very high steal time on some machines which is actually worthless for that high prices. If someone want to create pool or anything, just skip VPS resellers and go on dedicated.

PHP is no that bad in terms of performance, it depends specifically on task, but actually **everything can be written in any language** but with some languages it requires more work or time and with some less. I really do not understand why someone says that PHP is not efficient, it depends on code. But in case mining pool, let's make it clear. In case geth gets overloaded, then responses to php scripts may take longer which will cause php compiler to slow down etc... It depends on configuration. Running good efficient pool requires few nodes and few servers to fairly balance load. But running pool with one machine and less than 500 workers should be easily possibly with that code and good configuration. 
Good configuration is the key, but this is only Github page with issues related to code itself, no point discuss here performance tips, but this is the simplest, maybe not best solution.

**sysctl -w net.ipv4.tcp_tw_recycle = 1**
or/and
**sysctl -w net.ipv4.tcp_tw_reuse = 1**

**Comment by mmitech** [comment]
@karek314 not trying to degrade your work, I said a couple of times that we really appreciate the work people like you do... but I give up arguing about PHP sucking at performance, I posted many tests and researches that debunk that.

This doesn't mean you should stop what you are doing, I've learned many things looking at your code. and I am looking at your LISK pool and its indeed cleaner than this one. I will give it a try later :)

**Comment by davembg** [comment]
@karek314 did a good job making a working model, totally agree.
PHP5, yes - not as efficient as node, go, c++ etc.
If you use HHVM, your performance does indeed rival that of lower-level languages.
HHVM is PHP, true - but pre-compiled byte code. Works fine for FaceBook, just sayin'.

Be careful re-using TCP connections in conjunction with conntrack. I had some issues.
