### ISSUE TITLE
Ton of "Invalid header on mined Block" errors

### ISSUE THREAD

**Issue by mmitech** [karek314/Ethereumpool.co---Ethereum-Mining-Pool-Full-Source#4]
I am getting a ton of "Invalid header on mined Block" errors:

 ```` "I0209 17:23:39.216880    2691 worker.go:296] Invalid header on mined block: nonce for #978466 [87944ce66e31181c41fe1a81e91974ee64e2c756f465069948c83e33411bd25b…] is invalid (got 566349377610747962)````

at this point I am really not sure if the problem is with geth or process_work script.

**Comment by karek314** [comment]
It's normal behavior, it means script works, and pass 'shares' to geth node to check if this share might be correct block. You can firstly check if this share difficulty is under current network target and do not pass it to geth, but this will harm entire pool revenue since POW difficulty verification is slow, and in this time other node may submit the same block. Hope it's clear now :)

**Comment by mmitech** [comment]
OK I understand, but I get like 80% of this invalids, is this normal ?

**Comment by karek314** [comment]
If you are still referring to "Invalid header on mined block" then 99% should be invalid or even more, since valid response remain mined block.

**Comment by mmitech** [comment]
Excellent, thank you.
